# Generated by Django 3.0.5 on 2023-04-15 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_whenPublished',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 6, 0, 28, 241796), verbose_name='Date Published'),
        ),
    ]
