# Generated by Django 3.0.5 on 2023-04-15 06:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230415_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_whenPublished',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 6, 1, 31, 845970, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
