# Generated by Django 3.0.5 on 2023-04-17 13:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230415_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_no', models.PositiveIntegerField()),
                ('chapter_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=200)),
                ('note_summary', models.TextField()),
                ('note_whenPublished', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
                ('note_chapter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Chapter', verbose_name='Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Chapter', verbose_name='Chapter'),
        ),
    ]
