# Generated by Django 3.0.5 on 2023-04-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230417_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_chapter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Chapter', verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_chapter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Chapter', verbose_name='Chapter'),
        ),
    ]
