# Generated by Django 3.0.5 on 2023-04-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230417_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_author',
            field=models.CharField(default='', max_length=200),
        ),
    ]
