# Generated by Django 3.0.5 on 2023-04-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_note_note_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_summary',
            field=models.TextField(null=True),
        ),
    ]
