# Generated by Django 3.0.5 on 2023-04-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230418_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_fileurl',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
