name: Notesite Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysupersecretpassword
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: notesite

        ports:
          - 5432:5432

        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run:  pip install -r requirements.txt && pip install django-autocomplete-light && pip install whitenoise && pip install django-tinymce && pip install psycopg2==2.8.6

      - name: Build And Test
        run: python3 manage.py migrate && python3 manage.py test
        env:
          PG_PASS: mysupersecretpassword
          DATABASE_HOST: localhost
          SECRET_KEY: testsecretkey